name: Java CI

on: push

permissions:
  contents: read

jobs:
  build:

    name: Maven build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3.11.0
      with:
        distribution: 'adopt'
        java-version: '17'
        java-package: jdk
        architecture: x64

    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2

    - name: Build with Maven
      run: mvn package

    - name: Upload
      if: ${{ github.repository_owner == 'Slimefun' && github.ref == 'refS/heads/main' }}
      run: |
        curl -v -X POST \
          -H 'Authorization: ${{ secrets.PUBLISH_TOKEN }}' \
          -H "X-Checksum: $(sha256sum target/e2e-test-plugin.jar | awk '{print $1}')" \
          --data-binary '@target/e2e-test-plugin.jar' \
          https://preview-builds.walshy.dev/upload/e2e-tester/main/latest
